version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app-image
    container_name: fastapi_app
    command: >
      bash -c "poetry run alembic upgrade head && poetry run uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - test_network

  db:
    image: postgres:16
    container_name: postgres_db
    env_file:
      - .env
    networks:
      - test_network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  test-api:
    image: app-image
    container_name: test_fastapi_app
    depends_on:
      - db
      - app
    env_file:
      - .env
    networks:
      - test_network
    entrypoint: >
      sh -c "
      poetry run pytest tests/src/test_user.py
      && poetry run pytest tests/src/test_board.py
      && poetry run pytest tests/src/test_column.py
      && poetry run pytest tests/src/test_tasks.py
      "

networks:
  test_network: