"""add creator and executor field in task table

Revision ID: ebb0606fa7fd
Revises: 4159020619f7
Create Date: 2024-10-16 17:53:36.489422

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ebb0606fa7fd"
down_revision: Union[str, None] = "4159020619f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task", sa.Column("creator_id", sa.Integer(), nullable=False)
    )
    op.add_column(
        "task", sa.Column("executor_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(None, "task", "users", ["executor_id"], ["id"])
    op.create_foreign_key(None, "task", "users", ["creator_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "task", type_="foreignkey")
    op.drop_constraint(None, "task", type_="foreignkey")
    op.drop_column("task", "executor_id")
    op.drop_column("task", "creator_id")
    # ### end Alembic commands ###
