"""add completed in task table

Revision ID: 0944fdf1bead
Revises: 14ff1d8785fb
Create Date: 2024-10-19 17:29:59.726664

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0944fdf1bead"
down_revision: Union[str, None] = "14ff1d8785fb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task",
        sa.Column(
            "completed", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task", "completed")
    # ### end Alembic commands ###
