"""add deleted_at field

Revision ID: 0c56397c7143
Revises: 993cf4240572
Create Date: 2024-10-17 14:38:00.618244

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0c56397c7143"
down_revision: Union[str, None] = "993cf4240572"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "board", sa.Column("deleted_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "column", sa.Column("deleted_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "task", sa.Column("deleted_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "users", sa.Column("deleted_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "deleted_at")
    op.drop_column("task", "deleted_at")
    op.drop_column("column", "deleted_at")
    op.drop_column("board", "deleted_at")
    # ### end Alembic commands ###
